name: Test Deploy

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, 'draft')!= true }}
    name: Test Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Node.js 24.x
        uses: actions/setup-node@main
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org


      - name: Install Globel Dependencies
        run: |
          npm install hexo-cli -g

      - name: Install Dependencies
        run: |
          npm install
      - name: Generate Public Files
        run: |
          # Restore last modified time
          git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
          echo ==========
          node -v && npm -v
          echo ==========
          npm ls --depth 0
          echo ==========
          hexo clean && hexo g


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
     
